import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./components/provider/Providers";
import AppWrapper from "./components/AppWrapper";
import ToastContainerConfig from "./components/ui/ToastContainerConfig";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Belle Femme - The Hair Salon</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ backgroundColor: "#000000" }}>
        <>
          <Providers>
            <AppWrapper>{children}</AppWrapper>
            <ToastContainerConfig />
          </Providers>
        </>
      </body>
    </html>
  );
}
